/*
 * (C) 2017 covers1624
 * All Rights Reserved
 */
package net.covers1624.forceddeobf.launch;

import javax.swing.*;
import java.awt.*;

//Simple gui for asking mappings.
public class MappingsGui extends JDialog {

    public DummyFrame dummyParent;
    public JComboBox<String> comboBox;
    public JTextField textField;
    public JButton okButton;

    public MappingsGui() {
        super(new DummyFrame("Select Mappings"), true);
        dummyParent = (DummyFrame) getParent();
        initComponents();
    }

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
        if (!b) {
            dummyParent.setVisible(b);
        }
    }

    //This is auto generated by netbeans, shout out to brandon3055 for creating the gui.
    @SuppressWarnings ("unchecked")
    private void initComponents() {

        comboBox = new JComboBox<>();
        okButton = new JButton();
        JLabel jLabel1 = new JLabel();
        JSeparator jSeparator1 = new JSeparator();
        JLabel jLabel2 = new JLabel();
        textField = new JTextField();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        okButton.setText("OK");

        jLabel1.setText("Select from compatible mappings:");

        jLabel2.setText("Or enter custom mappins:");

        //@formatter:off
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator1)
                                .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel2)
                                                .addComponent(comboBox, GroupLayout.PREFERRED_SIZE, 194, GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(textField))
                        .addContainerGap())
                .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(okButton, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addContainerGap())
        );
        //@formatter:on

        pack();
        centerOnTheFuckingScreen(this);
    }

    private static void centerOnTheFuckingScreen(Component component) {
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Point centerPoint = ge.getCenterPoint();

        int centerX = (int) centerPoint.getX();
        int centerY = (int) centerPoint.getY();
        component.setLocation(centerX - (component.getWidth() / 2), Math.max(0, centerY - (component.getHeight() / 2)));
    }

    public static class DummyFrame extends JFrame {

        public DummyFrame(String title) {
            super(title);
            setUndecorated(true);
            setVisible(true);
            setLocationRelativeTo(null);
        }
    }
}
